version: '3.8'
services:
  oracle-21:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe-21
    restart: always
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: password
      ORACLE_DATABASE: ORCL
      APP_USER: app_user
      APP_USER_PASSWORD: password
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
