DROP USER super_schema CASCADE;
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER super_schema IDENTIFIED BY super_password;
GRANT ALL PRIVILEGES TO SUPER_SCHEMA;
GRANT SYSDBA TO SUPER_SCHEMA CONTAINER=ALL;


-- GRANT DBA TO ADMIN_SCHEMA CONTAINER=ALL;